name:  DEployment 
on:
    push:
        branches:
        - master
jobs:
    job1:
        runs-on: ubuuntu-latest
        steps:
        - name: "Checkout"
          uses: actions/checkout@v4

        - name: "Build the image"
          run: |
             docker build -t 14richard-dev/testimage100 .

        - name: "Push to DockerHub"
          run: |
            docker login -u 14richard-dev -p ${{ secrets.DOCKER_PASSWORD }}
            docker push 14richard-dev/testimage100
            echo "Image pushed successfully!"

    jobs2:
         runs-on: ubuuntu-latest
         needs: job1
         steps:
         - name: "Confirms the job"
           run: |
              echo "This is the second job"

         - name: "Checkout"
           uses: actions/checkout@v4
           with:
             name: "sample-artifact"
             path: "index.html"
             retention-days: 60


         - name: "Uploads as a second artifact"
           uses: actions/upload-artifact@v4
           with:
             name: "sample-artifact2"
             path: "index.html"
             retention-days: 60

         - name: "Pull the image from dockerhub into environment"
           run: |
              docker pull 14richard-dev/testimage100
              echo "Image pulled successfully"
              docker run -d -p 8080:80 14richard-dev/testimage100 


  